AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  suptech-supervisory-prompts

  Sample SAM Template for suptech-supervisory-records

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  PromptsTableName:
    Type: String
    Default: table
  BedrockModelId:
    Type: String
    Default: model
  S3BucketName:
    Type: String
    Default: bucket
  SupervisoryRecordsTableName:
    Type: String
    Default: table
  SupervisoryRecordsStreamArn:
    Type: String
    Default: stream

Resources:
  RegulatoryCompliancePromptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref PromptsTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: version
          AttributeType: N
        - AttributeName: application
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: application-type-index
          KeySchema:
            - AttributeName: application
              KeyType: HASH
            - AttributeName: type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  RegulatoryCompliancePromptFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/regulatory-compliance-prompt/
      Handler: app.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 60
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowMethods: 
            - "*"
          AllowHeaders: 
            - "*"
          AllowOrigins: 
            - "*"
      Role: !GetAtt RegulatoryCompliancePromptFunctionRole.Arn
      Environment:
        Variables:
          SYSTEM_PROMPTS_TABLE_NAME: !Ref PromptsTableName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          S3_BUCKET_NAME: !Ref S3BucketName
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  MetadataInsertionPromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/metadata-insertion-prompt/
      Handler: app.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 60
      Architectures:
        - x86_64
      Role: !GetAtt MetadataInsertionPromptFunctionRole.Arn
      Environment:
        Variables:
          SUPERVISORY_RECORDS_TABLE_NAME: !Ref SupervisoryRecordsTableName
          S3_BUCKET_NAME: !Ref S3BucketName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Events:
        DynamoDBTrigger:
          Type: DynamoDB
          Properties:
            Stream: !Ref SupervisoryRecordsStreamArn
            StartingPosition: LATEST
            BatchSize: 10
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  RegulatoryCompliancePromptFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
  
  MetadataInsertionPromptFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess