AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  suptech-supervisory-prompts

  Sample SAM Template for suptech-supervisory-records

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  PromptsTableName:
    Type: String
    Default: table
  WarrantyAnalysisTableName:
    Type: String
    Default: table
  LetterAnalysisTableName:
    Type: String
    Default: table
  BedrockModelId:
    Type: String
    Default: model
  WarrantyReportsBucketName:
    Type: String
    Default: bucket
  RecordsBucketName:
    Type: String
    Default: bucket
  CsvAnalysisBucketName:
    Type: String
    Default: bucket
  ProcessedRecordsBucketName:
    Type: String
    Default: bucket
  SupervisoryRecordsTableName:
    Type: String
    Default: table
  SupervisoryRecordsMetadataTableName:
    Type: String
    Default: table
  SupervisoryRecordsStreamArn:
    Type: String
    Default: stream
  InteractionWebSocketQueueUrl:
    Type: String
    Default: queue
  StageName:
    Type: String
    Default: develop
  SaveCSVFlag:
    Type: String
    Default: "true"
  PdfJsLayer:
    Type: String
    Default: layer
  MetadataExtractionServiceUrl:
    Type: String
    Default: url
  KafkaBrokers:
    Type: String
    Default: brokers
  WarrantyRRTableName:
    Type: String
    Default: table
  WarrantyITTableName:
    Type: String
    Default: table
  LetterRRTableName:
    Type: String
    Default: table
  LetterITTableName:
    Type: String
    Default: table

Resources:
  CsvBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CsvAnalysisBucketName
  ProcessedRecordsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedRecordsBucketName

  RegulatoryComplianceIntelligenceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      OpenApiVersion: 3.0.1
      DefinitionBody: # an OpenApi definition
        Fn::Transform:
          Name: "AWS::Include"
          Parameters:
            Location: "infrastructure/openapi.yml"
      EndpointConfiguration:
        Type: REGIONAL
      BinaryMediaTypes:
        - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        - "application/pdf"

  RegulatoryCompliancePromptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref PromptsTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: version
          AttributeType: N
        - AttributeName: application
          AttributeType: S
        - AttributeName: documentType
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: application-documentType-index
          KeySchema:
            - AttributeName: application
              KeyType: HASH
            - AttributeName: documentType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  WarrantyRegulatoryReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref WarrantyRRTableName
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: CODGR
          AttributeType: S
        - AttributeName: CODINSCRIPCION
          AttributeType: S
        - AttributeName: PERIOD_YEAR
          AttributeType: N
        - AttributeName: PERIOD_MONTH
          AttributeType: N
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: codgr-index
          KeySchema:
            - AttributeName: CODGR
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: CODINSCRIPCION-index
          KeySchema:
            - AttributeName: CODINSCRIPCION
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: periodYear-periodMonth-index
          KeySchema:
            - AttributeName: PERIOD_YEAR
              KeyType: HASH
            - AttributeName: PERIOD_MONTH
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 100
        MaxWriteRequestUnits: 100

  WarrantyInternalTablesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref WarrantyITTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: codgr
          AttributeType: S
        - AttributeName: period
          AttributeType: S
        - AttributeName: period_year
          AttributeType: N
        - AttributeName: period_month
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: codgr-period-index
          KeySchema:
            - AttributeName: codgr
              KeyType: HASH
            - AttributeName: period
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: period_year-period_month-index
          KeySchema:
            - AttributeName: period_year
              KeyType: HASH
            - AttributeName: period_month
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 100
        MaxWriteRequestUnits: 100

  BankGuaranteeRegulatoryReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref LetterRRTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: ccr
          AttributeType: S
        - AttributeName: period_year
          AttributeType: N
        - AttributeName: period_month
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ccr-index
          KeySchema:
            - AttributeName: ccr
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: period_year-period_month-index
          KeySchema:
            - AttributeName: period_year
              KeyType: HASH
            - AttributeName: period_month
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 100
        MaxWriteRequestUnits: 100

  BankGuaranteeInternalTablesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref LetterITTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: codigo_credito
          AttributeType: S
        - AttributeName: period_year
          AttributeType: N
        - AttributeName: period_month
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: codigo_credito-index
          KeySchema:
            - AttributeName: codigo_credito
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: period_year-period_month-index
          KeySchema:
            - AttributeName: period_year
              KeyType: HASH
            - AttributeName: period_month
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 100
        MaxWriteRequestUnits: 100



  GetDocumentsAnalysisSheetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/get-documents-analysis-sheet/
      Handler: app.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 60
      Architectures:
        - x86_64
      Role: !GetAtt GetDocumentsAnalysisSheetFunctionRole.Arn
      Environment:
        Variables:
          S3_CSV_BUCKET_NAME: !Ref CsvAnalysisBucketName
      Events:
        GetDocumentAnalysisSheetApi:
          Type: Api
          Properties:
            Path: /regulatory-compliance-intelligence/documents-analysis-sheet/{uuid}
            Method: GET
            RestApiId: !Ref RegulatoryComplianceIntelligenceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  DocumentHighlightFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/document-highlight/
      Handler: app.handler
      Runtime: nodejs22.x
      MemorySize: 512
      Timeout: 120
      Architectures:
        - x86_64
      Role: !GetAtt DocumentHighlightFunctionRole.Arn
      Environment:
        Variables:
          S3_RECORDS_BUCKET_NAME: !Ref RecordsBucketName
          S3_CSV_ANALYSIS_BUCKET_NAME: !Ref CsvAnalysisBucketName
          SUPERVISORY_RECORDS_TABLE_NAME: !Ref SupervisoryRecordsTableName
      Events:
        DocumentHighlightApi:
          Type: Api
          Properties:
            Path: /regulatory-compliance-intelligence/pdf/highlight/{messageId}/{recordKey}
            Method: GET
            RestApiId: !Ref RegulatoryComplianceIntelligenceApi
      Layers:
        - !Ref PdfJsLayer
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        External:
          - pdfjs-dist
        EntryPoints:
          - app.ts

  RegulatoryCompliancePromptFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/regulatory-compliance-prompt/
      Handler: app.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 60
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"
          AllowOrigins:
            - "*"
      Role: !GetAtt RegulatoryCompliancePromptFunctionRole.Arn
      Environment:
        Variables:
          SYSTEM_PROMPTS_TABLE_NAME: !Ref PromptsTableName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          S3_DOCUMENTS_BUCKET_NAME: !Ref RecordsBucketName
          S3_CSV_BUCKET_NAME: !Ref CsvAnalysisBucketName
          S3_WARRANTY_REPORTS_BUCKET_NAME: !Ref WarrantyReportsBucketName
          S3_LETTER_REPORTS_BUCKET_NAME: !Ref WarrantyReportsBucketName
          WARRANTY_ANALYSIS_TABLE_NAME: !Ref WarrantyAnalysisTableName
          LETTER_ANALYSIS_TABLE_NAME: !Ref LetterAnalysisTableName
          SAVE_CSV_FLAG: !Ref SaveCSVFlag
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  ProcessDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 60
      Architectures:
        - x86_64
      Role: !GetAtt ProcessDocumentsFunctionRole.Arn
      Environment:
        Variables:
          SUPERVISORY_RECORDS_TABLE_NAME: !Ref SupervisoryRecordsTableName
          SUPERVISORY_RECORDS_METADATA_TABLE_NAME: !Ref SupervisoryRecordsMetadataTableName
          SYSTEM_PROMPTS_TABLE_NAME: !Ref PromptsTableName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          S3_DOCUMENTS_BUCKET_NAME: !Ref RecordsBucketName
          S3_PROCESSED_DOCUMENTS_BUCKET_NAME: !Ref ProcessedRecordsBucketName
          KAFKA_BROKERS: !Ref KafkaBrokers
          NODE_OPTIONS: "--enable-source-maps"
          INTERACTION_WEBSOCKET_QUEUE_URL: !Ref InteractionWebSocketQueueUrl
          HOME: "/tmp"
      Events:
        DynamoDBTrigger:
          Type: DynamoDB
          Properties:
            Stream: !Ref SupervisoryRecordsStreamArn
            StartingPosition: LATEST
            BatchSize: 10
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
    Metadata:
      DockerTag: process-documents.v1
      DockerContext: ./functions/process-documents
      Dockerfile: Dockerfile

  ProcessCsvDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/process-csv-documents/
      Handler: app.handler
      Runtime: nodejs22.x
      MemorySize: 512
      Timeout: 120
      Architectures:
        - x86_64
      Role: !GetAtt ProcessCsvDocumentsFunctionRole.Arn
      Environment:
        Variables:
          S3_DOCUMENTS_BUCKET_NAME: !Ref RecordsBucketName
          WARRANTY_RR_TABLE: !Ref WarrantyRRTableName
          WARRANTY_IT_TABLE: !Ref WarrantyITTableName
          LETTER_RR_TABLE: !Ref LetterRRTableName
          LETTER_IT_TABLE: !Ref LetterITTableName
          NODE_OPTIONS: "--enable-source-maps"
          INTERACTION_WEBSOCKET_QUEUE_URL: !Ref InteractionWebSocketQueueUrl
      Events:
        DynamoDBTrigger:
          Type: DynamoDB
          Properties:
            Stream: !Ref SupervisoryRecordsStreamArn
            StartingPosition: LATEST
            BatchSize: 10
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  RegulatoryCompliancePromptFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess

  DocumentHighlightFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  ProcessDocumentsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  ProcessCsvDocumentsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  GetDocumentsAnalysisSheetFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
