AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  suptech-supervisory-records

  Sample SAM Template for suptech-supervisory-records

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  PromptsTableName:
    Type: String
    Default: table
  BedrockModelId:
    Type: String
    Default: model
  S3BucketName:
    Type: String
    Default: bucket

Resources:
  RegulatoryCompliancePromptFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/regulatory-compliance-prompt/
      Handler: app.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        RegulatoryCompliancePrompt:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /regulatory-compliance/prompt
            Method: post
      Environment:
        Variables:
          SYSTEM_PROMPTS_TABLE_NAME: !Ref PromptsTableName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          S3_BUCKET_NAME: !Ref S3BucketName
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
      
 

