export interface WarrantyRegulatoryReport {
  ID: string;
  BLOQ: number | null;
  CC: string | null;
  CCLQGR: string | null;
  CGR: number | null;
  COBGR: number | null;
  CODINSCRIPCION: string | null;
  CODGR: string | null;
  FBLOQ: string | null;
  FCONS: string | null;
  FINPOL: null;
  FUVAL: string | null;
  FVEPOL: string | null;
  IDREPEV: string | null;
  IGRC: number | null;
  MONGR: number | null;
  NCLQGR: string | null;
  NINS: string;
  PERIOD_MONTH: number;
  PERIOD_YEAR: number;
  period: string;
  POL: string | null;
  recordId: string;
  REPEV: string | null;
  supervisedEntityId: string;
  TGR: string | null;
  VANX: number | null;
  VBC: number | null;
  VCOM: number | null;
  VCOM_OTH: number | null;
  VCOM_PEN: number | null;
  VCOM_USD: number | null;
  VCONS: number | null;
  VREA: number | null;
  VREA_OTH: number | null;
  VREA_PEN: number | null;
  VREA_USD: number | null;
}
