openapi: 3.0.1
info:
  title: Regulatory Compliance Intelligence API
  description: "OpenAPI contract for Regulatory Compliance Intelligence API"
  version: 1.0.0
  contact: {}
tags:
  - name: Suptech

x-amazon-apigateway-request-validators:
  full:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false
  parameters:
    validateRequestParameters: true
    validateRequestBody: false

paths:
  /regulatory-compliance-intelligence/documents-analysis-sheet/{uuid}:
    get:
      operationId: documentAnalysisSheet
      x-amazon-apigateway-request-validator: "full"
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDocumentsAnalysisSheetFunctionArn}/invocations
            - GetDocumentsAnalysisSheetFunctionArn:
                Fn::GetAtt: [GetDocumentsAnalysisSheetFunction, Arn]
        type: aws_proxy
      parameters:
        - name: uuid
          schema:
            type: string
          in: path
          required: true
          description: UUID of the document to analyze
      responses:
        "200":
          $ref: "#/components/responses/DocumentAnalysisSheetResponse"
        "500":
          $ref: "#/components/responses/ErrorResponse"

components:
  responses:
    DocumentAnalysisSheetResponse:
      description: Document Analysis Sheet Response
      content:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
          schema:
            type: string
            format: binary
         
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
        - message
